version: '3'

services:
  web-django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - django-flask-net

networks:
  django-flask-net:
    external: true
